In [1]:
#자주 사용하는 패키지를 임포트
import matplotlib as mpl
import matplotlib.pylab as plt
from mpl_toolkits.mplot3d import Axes3D
import seaborn as sns
import numpy as np
import scipy as sp
import pandas as pd
import statsmodels.api as sm

## p.11

In [2]:
a = np.array([1,2])
np.linalg.norm(a) # 벡터의 norm 구하기

np.float64(2.23606797749979)

In [3]:
b = 2*a
c = -2*a
print(a)
print(b)
print(c)

[1 2]
[2 4]
[-2 -4]


In [4]:
## p.24

In [5]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])
a1 = A[0,:]
print(a1)

[1 2 3]


In [6]:
a1 @ B

array([22, 28])

In [7]:
b1 = B[:,0]
print(b1)

[1 3 5]


In [8]:
A @ b1

array([22, 49])

In [9]:
C = A @ B
print(C)

[[22 28]
 [49 64]]


In [10]:
C = np.dot(A,B)
print(C)

[[22 28]
 [49 64]]


## p.26

In [11]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
C = np.array([[9,8],[7,6]])
A@B

array([[19, 22],
       [43, 50]])

In [12]:
B@A # AB가 BA와 같지 않음을 확인

array([[23, 34],
       [31, 46]])

In [13]:
A@(B+C)

array([[42, 42],
       [98, 98]])

In [14]:
A@B+A@C # A(B+C) = AB + AC

array([[42, 42],
       [98, 98]])

In [15]:
(A+B)@C

array([[110,  96],
       [174, 152]])

In [16]:
A@C+B@C # (A+B)C = AC + BC

array([[110,  96],
       [174, 152]])

## p.29

In [17]:
(A+B).T

array([[ 6, 10],
       [ 8, 12]])

In [18]:
A.T+B.T # (A+B).T = A.T + B.T

array([[ 6, 10],
       [ 8, 12]])

In [19]:
(A@B).T

array([[19, 43],
       [22, 50]])

In [20]:
B.T@A.T # (A@B).T  = B.T + A.T

array([[19, 43],
       [22, 50]])

In [21]:
A.T@B.T # (A@B).T 가 A.T + B.T와 같지 않음

array([[23, 31],
       [34, 46]])

## p.36

In [22]:
np.trace(np.eye(3))

np.float64(3.0)

## p.38

In [24]:
a = np.array([1,2,3])
b = np.array([1,2])
a+b

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [25]:
a = np.array([1,2,3])
b = np.array([1])
a+b

array([2, 3, 4])

## p.40

In [26]:
a = np.array(np.arange(1,13)).reshape(4,3)
b = np.array([1,0,1])
print(a + b)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


## p.42

In [27]:
np.arange(3).reshape(3,1) + np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

## p.44

In [28]:
a = np.array(np.arange(0,3))
print(a)

[0 1 2]


In [29]:
a = np.array(np.arange(0,6)).reshape(2,3)
print(a)

[[0 1 2]
 [3 4 5]]


In [30]:
a = np.array(np.arange(0,24)).reshape(4,2,3)
print(a)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


In [31]:
a = np.array(np.arange(0,120)).reshape(5,4,2,3)
print(a)

[[[[  0   1   2]
   [  3   4   5]]

  [[  6   7   8]
   [  9  10  11]]

  [[ 12  13  14]
   [ 15  16  17]]

  [[ 18  19  20]
   [ 21  22  23]]]


 [[[ 24  25  26]
   [ 27  28  29]]

  [[ 30  31  32]
   [ 33  34  35]]

  [[ 36  37  38]
   [ 39  40  41]]

  [[ 42  43  44]
   [ 45  46  47]]]


 [[[ 48  49  50]
   [ 51  52  53]]

  [[ 54  55  56]
   [ 57  58  59]]

  [[ 60  61  62]
   [ 63  64  65]]

  [[ 66  67  68]
   [ 69  70  71]]]


 [[[ 72  73  74]
   [ 75  76  77]]

  [[ 78  79  80]
   [ 81  82  83]]

  [[ 84  85  86]
   [ 87  88  89]]

  [[ 90  91  92]
   [ 93  94  95]]]


 [[[ 96  97  98]
   [ 99 100 101]]

  [[102 103 104]
   [105 106 107]]

  [[108 109 110]
   [111 112 113]]

  [[114 115 116]
   [117 118 119]]]]


## p.45

In [32]:
a = np.array(np.arange(0,6)).reshape(2,3)
print(a)
print('sum(axis=0):',np.sum(a, axis=0))

[[0 1 2]
 [3 4 5]]
sum(axis=0): [3 5 7]


## p.46

In [33]:
print('max(axis=1):',np.max(a, axis=1))

max(axis=1): [2 5]


In [34]:
# 다른 예제
a = np.array(np.arange(0,24)).reshape(4,2,3)
print(np.sum(a, axis=0))
print(np.max(a, axis=1))

[[36 40 44]
 [48 52 56]]
[[ 3  4  5]
 [ 9 10 11]
 [15 16 17]
 [21 22 23]]


## p.48

In [35]:
A = np.array([[1,1,0],[0,1,1],[1,1,1]])
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1]])

In [36]:
Ainv = np.linalg.inv(A)
Ainv

array([[ 0., -1.,  1.],
       [ 1.,  1., -1.],
       [-1.,  0.,  1.]])

In [37]:
A @ Ainv

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
Ainv @ A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## p.51

In [39]:
B = np.array([[1,2],[3,4]])
Binv = np.linalg.inv(B)
Binv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [40]:
np.linalg.inv(B.T)

array([[-2. ,  1.5],
       [ 1. , -0.5]])

In [41]:
A = np.array([[5,6],[7,8]])
Ainv = np.linalg.inv(A)
Ainv

array([[-4. ,  3. ],
       [ 3.5, -2.5]])

In [42]:
np.linalg.inv(A@B)

array([[11.5 , -8.5 ],
       [-7.75,  5.75]])

In [43]:
Binv@Ainv

array([[11.5 , -8.5 ],
       [-7.75,  5.75]])

## p.54

In [44]:
A1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
A2 = np.array([[1,1,0],[1,0,1],[0,1,1]])
A3 = np.array([[2,1,1],[1,0,1],[1,1,0]])
A4 = np.array([[2,4,1],[1,2,0.5],[0.5,1,0.25]])
print(np.linalg.matrix_rank(A1))
print(np.linalg.matrix_rank(A2))
print(np.linalg.matrix_rank(A3))
print(np.linalg.matrix_rank(A4))

3
3
2
1


## p.56

In [45]:
A = np.array([[1,1,0],[0,1,1],[1,1,1]])
Ainv = np.linalg.inv(A)
b = np.array([[2],[2],[3]])
x = Ainv @ b
x

array([[1.],
       [1.],
       [1.]])

In [46]:
#검산
print(A)
print(b)
print(A@x-b)

[[1 1 0]
 [0 1 1]
 [1 1 1]]
[[2]
 [2]
 [3]]
[[0.]
 [0.]
 [0.]]


## p.58

In [47]:
A = np.array([[2,-5,4],[1,-2,1],[1,-3,3]])
B = np.array([[-3],[5],[10]])
x = np.linalg.solve(A,b)

LinAlgError: Singular matrix

## p.61

In [48]:
A = np.array([[2,-5,4],[1,-2,1],[1,-3,3]])
np.linalg.det(A)

np.float64(0.0)

In [49]:
A = np.array([[2,-1],[-1,2]])
np.linalg.det(A)

np.float64(2.9999999999999996)